function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[array[i], array[j]] = [array[j], array[i]]
    }
    return array
}

function assignCondition(stimuli_list) {
    let new_stimuli_list = []
    // Loop through unique styles
    for (let style of [...new Set(stimuli_list.map((a) => a.Style))]) {
        // Get all stimuli of this style
        var style_stimuli = stimuli_list.filter((a) => a.Style == style)

        // Shuffle style_stimuli
        style_stimuli = shuffleArray(style_stimuli) // Custom function defined above

        // Assign condition to each image
        let conditions = ["AI", "Human", "Forgery"]
        let third = Math.floor(style_stimuli.length / 3) // Base number of images for each condition
        let remainder = style_stimuli.length % 3 // Extra images

        let index = 0
        for (let i = 0; i < 3; i++)
            for (let j = 0; j < third; j++) {
                style_stimuli[index].Condition = conditions[i]
                index++
            }

        let shuffledConditions = shuffleArray(conditions) // Shuffle conditions to assign extra images to random conditions
        for (let i = 0; i < remainder; i++) {
            style_stimuli[index].Condition = shuffledConditions[i]
            index++
        }

        // Add to new_stimuli_list
        new_stimuli_list.push(...style_stimuli)
    }
    return shuffleArray(new_stimuli_list)
}



// Variables ===================================================================
var fiction_trialnumber = 1
/* var color_cues = shuffleArray(["red", "blue", "green"])

color_cues = {
    AI: color_cues[0],
    Human: color_cues[1],
    Forgery: color_cues[2],
}

var text_cue = {
    AI: "AI-Generated",
    Human: "Original",
    Forgery: "Human Forgery",
} */

stimuli = assignCondition(stimuli_list)


var fiction_preloadstims = {
    type: jsPsychPreload,
    images: stimuli_list.map((a) => "stimuli/stimuli/" + a.Item),
    message: "Please wait while the experiment is loading in (it can take a few minutes).",
}


/* fiction 2 */

var fiction_fixation = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: "<div  style='font-size:500%; position:fixed; text-align: center; top:50%; bottom:50%; right:20%; left:20%'>+</div>",
    choices: ["s"],
    trial_duration: 750,
    save_trial_parameters: { trial_duration: true },
    data: { screen: "fiction_fixation" },
}


 var fiction_showimage = {
    type: jsPsychImageKeyboardResponse,
    stimulus: function () {
        return "stimuli/stimuli/" + jsPsych.evaluateTimelineVariable("Item")
    },
    stimulus_width: function () {
        let ratio = jsPsych.evaluateTimelineVariable("Width") / jsPsych.evaluateTimelineVariable("Height")
        return Math.round(Math.min(0.9 * window.innerHeight * ratio, 0.9 * window.innerWidth))
    },

    stimulus_height: function () {
        let ratio = jsPsych.evaluateTimelineVariable("Width") / jsPsych.evaluateTimelineVariable("Height")
        return Math.round(Math.min((0.9 * window.innerWidth) / ratio, 0.9 * window.innerHeight))
    },
    trial_duration: 1500,
    choices: ["s"],
    save_trial_parameters: { trial_duration: true },
    data: function () {
        return {
            screen: "fiction_image",
            trial_number: fiction_trialnumber,
            item: jsPsych.evaluateTimelineVariable("Item"),
        }
    },
    on_finish: function () {
        fiction_trialnumber += 1
    },
} 


var fiction_ratings = {
    type: jsPsychSurvey,
    survey_json: {
        goNextPageAutomatic: false,
        showQuestionNumbers: false,
        showNavigationButtons: true,
        pages: [
            {
                elements: [
                    {
                        type: "html",
                        name: "Instructions",
                        html: "The following questions relate to your experience of viewing the artworks in the first phase of the previous study.",
                    },
                    {
                        type: "slider",
                        name: "Reality",
                        title: "I thought this artwork was...",
                        description: "Was the artwork painted by a person or generated by an AI? Drag the slider according to where you best remember placing the slider in the previous study.",
                        isRequired: true,
                        // minWidth: "200%",
                        // maxWidth: "200%",
                        min: -100,
                        max: 100,
                        step: 1,
                        customLabels: [
                            {
                                value: -100,
                                text: " AI-generated",
                            },
                            {
                                value: 100,
                                text: "Human creation",
                            },
                        ],
                        // defaultValue: 0,
                    },
                    {
                        type: "slider",
                        name: "Authenticity",
                        title: "I thought this artwork was a(n)...",
                        description: "Is the artwork original and unique, or was it made to copy an existing artwork or artist? Drag the slider according to where you best remember placing the slider in the previous study.",
                        isRequired: true,
                        // minWidth: "200%",
                        // maxWidth: "200%",
                        min: -100,
                        max: 100,
                        step: 1,
                        customLabels: [
                            {
                                value: -100,
                                text: "Copy / Forgery",
                            },
                            {
                                value: 100,
                                text: "Original Creation",
                            },
                        ],
                        // defaultValue: 0,
                    },
                     {
                        type: "slider",
                        name: "Familiarity",
                        title: "This artwork is...",
                        description: "To what extent do you recall seeing this artwork in the previous study?",
                        isRequired: true,
                        // minWidth: "200%",
                        // maxWidth: "200%",
                        min: -100,
                        max: 100,
                        step: 1,
                        customLabels: [
                            {
                                value: -100,
                                text: "Unfamiliar",
                            },
                            {
                                value: 100,
                                text: "Familiar",
                            },
                        ],
                        // defaultValue: 0,
                    },
                    {
                        type: "rating",
                        name: "Artwork category",
                        title: "In the first phase of the previous study, this artwork was labelled as...",
                        isRequired: true,
                        css_classes: ["colored-scale"],
                        displayMode: "buttons",
                        rateValues: [
                            { value: 0, text: "Original" },
                            { value: 1, text: "AI-generated" },
                            { value: 2, text: "Human forgery" },
                        ],
                    },
                ],
            },
        ],
    },
    data: {
        screen: "fiction_ratings",
    },
}


var fiction_phase = {
    timeline_variables: shuffleArray(stimuli),
    timeline: [fiction_fixation, fiction_showimage, fiction_ratings],
}
